AWSTemplateFormatVersion: "2010-09-09"

Resources:
  ApiGatewayDomainName:
    Type: AWS::ApiGatewayV2::DomainName
    Properties:
      DomainName: ${self:provider.environment.DOMAIN_NAME}
      DomainNameConfigurations:
        - EndpointType: REGIONAL
          CertificateArn: arn:aws:acm:us-east-1:652325596088:certificate/a75cb789-3935-46cd-91ec-5fb37d59fa9b

  ApiGatewayApiMapping:
    Type: AWS::ApiGatewayV2::ApiMapping
    Properties:
      ApiId: !Ref HttpApi
      DomainName: ${self:provider.environment.DOMAIN_NAME}
      Stage: !Ref HttpApiStage
    DependsOn:
      - ApiGatewayDomainName
      - HttpApiStage

  Route53HealthCheck:
    Type: 'AWS::Route53::HealthCheck'
    Properties:
      HealthCheckConfig:
        FailureThreshold: 1
        FullyQualifiedDomainName: ${self:provider.environment.DOMAIN_NAME}
        Port: 443
        RequestInterval: 30
        ResourcePath: '/api/health'
        Type: HTTPS
      HealthCheckTags:
        - Key: Name
          Value: ${self:service}-${self:provider.stage}

  Route53RecordSet:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneName: '${self:provider.environment.HOSTED_ZONE}.'
      Name: ${self:provider.environment.DOMAIN_NAME}
      ResourceRecords:
        - !GetAtt ApiGatewayDomainName.RegionalDomainName
      TTL: 30
      Type: CNAME
      Region: ${self:provider.region}
      HealthCheckId: !Ref Route53HealthCheck
      SetIdentifier: ${self:service}-${self:provider.stage}-${self:provider.region}-latency

  SSMParameterHealthCheck:
    Type: AWS::SSM::Parameter
    Properties:
      Name: '/health-check/${self:provider.region}/is-healthy'
      AllowedPattern: ^true|false$
      Description: 'Regional health check'
      Type: String
      Value: 'true'