- '!.env*'
- '!.eslint*'
- '!.idea/**'
- '!.jest-tmp/**'
- '!.nuxt'
- '!.yarn'
- '!node_modules/**/*.md'
- '!node_modules/**/*.txt'
- '!node_modules/**/.tmp/**'
- '!node_modules/**/coverage/**'
- '!node_modules/**/examples/**'
- '!node_modules/**/test/**'
- '!node_modules/**/tests/**'
- '!sitemaps/**'
- '!test/**'