version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - yarn install --frozen-lockfile
  build:
    commands:
      - yarn sls:build --stage $STAGE --region $AWS_REGION
      - yarn sls:deploy --stage $STAGE --region $AWS_REGION