AWSTemplateFormatVersion: "2010-09-09"
Description: "The AWS CloudFormation template for creating the PROD CodeBuild Project"

Resources:
  CodeBuildProjectProd:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: 'watch-prod-us-east-1-codebuild'
      ServiceRole: arn:aws:iam::652325596088:role/watch-codebuild-role
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        EnvironmentVariables:
          - Name: STAGE
            Value:  prod
        Image: aws/codebuild/standard:6.0
        Type: LINUX_CONTAINER
      Source:
        Type: CODEPIPELINE
        BuildSpec: infrastructure/buildspec.yml