AWSTemplateFormatVersion: "2010-09-09"
Description: "The AWS CloudFormation template for creating the STG S3 Artifacts Bucket"

Resources:
  S3BucketStg:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: Retain
    Properties:
      BucketName: watch-stg-us-east-1-artifacts